services:
  - type: web
    name: skysurge
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: skysurge
          property: port
    # Environment variables that need to be set in Render dashboard:
    # MONGODB_URI - MongoDB Atlas connection string
    # FIREBASE_PROJECT_ID - Firebase project ID
    # FIREBASE_PRIVATE_KEY_ID - Firebase private key ID
    # FIREBASE_PRIVATE_KEY - Firebase private key (with \n for newlines)
    # FIREBASE_CLIENT_EMAIL - Firebase service account email
    # FIREBASE_CLIENT_ID - Firebase client ID
    # STRIPE_SECRET_KEY - Stripe secret key (optional)
    # STRIPE_PUBLISHABLE_KEY - Stripe publishable key (optional)
    # STRIPE_WEBHOOK_SECRET - Stripe webhook secret (optional)
